/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUsersRouteImport } from './routes/users/users'
import { Route as UsersAdduserRouteImport } from './routes/users/adduser'
import { Route as StoreStoresRouteImport } from './routes/store/stores'
import { Route as StoreAddstoreRouteImport } from './routes/store/addstore'
import { Route as RoleRoleRouteImport } from './routes/role/role'
import { Route as RoleAddroleRouteImport } from './routes/role/addrole'
import { Route as ProductProductsRouteImport } from './routes/product/products'
import { Route as ProductAddRouteImport } from './routes/product/add'
import { Route as UsersEditIdRouteImport } from './routes/users/edit/$id'
import { Route as StoreEditIdRouteImport } from './routes/store/edit/$id'
import { Route as RoleEditIdRouteImport } from './routes/role/edit/$id'
import { Route as ProductEditIdRouteImport } from './routes/product/edit/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsersRoute = UsersUsersRouteImport.update({
  id: '/users/users',
  path: '/users/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersAdduserRoute = UsersAdduserRouteImport.update({
  id: '/users/adduser',
  path: '/users/adduser',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreStoresRoute = StoreStoresRouteImport.update({
  id: '/store/stores',
  path: '/store/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreAddstoreRoute = StoreAddstoreRouteImport.update({
  id: '/store/addstore',
  path: '/store/addstore',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoleRoute = RoleRoleRouteImport.update({
  id: '/role/role',
  path: '/role/role',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleAddroleRoute = RoleAddroleRouteImport.update({
  id: '/role/addrole',
  path: '/role/addrole',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductsRoute = ProductProductsRouteImport.update({
  id: '/product/products',
  path: '/product/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductAddRoute = ProductAddRouteImport.update({
  id: '/product/add',
  path: '/product/add',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersEditIdRoute = UsersEditIdRouteImport.update({
  id: '/users/edit/$id',
  path: '/users/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreEditIdRoute = StoreEditIdRouteImport.update({
  id: '/store/edit/$id',
  path: '/store/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleEditIdRoute = RoleEditIdRouteImport.update({
  id: '/role/edit/$id',
  path: '/role/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductEditIdRoute = ProductEditIdRouteImport.update({
  id: '/product/edit/$id',
  path: '/product/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/product/add': typeof ProductAddRoute
  '/product/products': typeof ProductProductsRoute
  '/role/addrole': typeof RoleAddroleRoute
  '/role/role': typeof RoleRoleRoute
  '/store/addstore': typeof StoreAddstoreRoute
  '/store/stores': typeof StoreStoresRoute
  '/users/adduser': typeof UsersAdduserRoute
  '/users/users': typeof UsersUsersRoute
  '/product/edit/$id': typeof ProductEditIdRoute
  '/role/edit/$id': typeof RoleEditIdRoute
  '/store/edit/$id': typeof StoreEditIdRoute
  '/users/edit/$id': typeof UsersEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/product/add': typeof ProductAddRoute
  '/product/products': typeof ProductProductsRoute
  '/role/addrole': typeof RoleAddroleRoute
  '/role/role': typeof RoleRoleRoute
  '/store/addstore': typeof StoreAddstoreRoute
  '/store/stores': typeof StoreStoresRoute
  '/users/adduser': typeof UsersAdduserRoute
  '/users/users': typeof UsersUsersRoute
  '/product/edit/$id': typeof ProductEditIdRoute
  '/role/edit/$id': typeof RoleEditIdRoute
  '/store/edit/$id': typeof StoreEditIdRoute
  '/users/edit/$id': typeof UsersEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/product/add': typeof ProductAddRoute
  '/product/products': typeof ProductProductsRoute
  '/role/addrole': typeof RoleAddroleRoute
  '/role/role': typeof RoleRoleRoute
  '/store/addstore': typeof StoreAddstoreRoute
  '/store/stores': typeof StoreStoresRoute
  '/users/adduser': typeof UsersAdduserRoute
  '/users/users': typeof UsersUsersRoute
  '/product/edit/$id': typeof ProductEditIdRoute
  '/role/edit/$id': typeof RoleEditIdRoute
  '/store/edit/$id': typeof StoreEditIdRoute
  '/users/edit/$id': typeof UsersEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/product/add'
    | '/product/products'
    | '/role/addrole'
    | '/role/role'
    | '/store/addstore'
    | '/store/stores'
    | '/users/adduser'
    | '/users/users'
    | '/product/edit/$id'
    | '/role/edit/$id'
    | '/store/edit/$id'
    | '/users/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/product/add'
    | '/product/products'
    | '/role/addrole'
    | '/role/role'
    | '/store/addstore'
    | '/store/stores'
    | '/users/adduser'
    | '/users/users'
    | '/product/edit/$id'
    | '/role/edit/$id'
    | '/store/edit/$id'
    | '/users/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/product/add'
    | '/product/products'
    | '/role/addrole'
    | '/role/role'
    | '/store/addstore'
    | '/store/stores'
    | '/users/adduser'
    | '/users/users'
    | '/product/edit/$id'
    | '/role/edit/$id'
    | '/store/edit/$id'
    | '/users/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ProductAddRoute: typeof ProductAddRoute
  ProductProductsRoute: typeof ProductProductsRoute
  RoleAddroleRoute: typeof RoleAddroleRoute
  RoleRoleRoute: typeof RoleRoleRoute
  StoreAddstoreRoute: typeof StoreAddstoreRoute
  StoreStoresRoute: typeof StoreStoresRoute
  UsersAdduserRoute: typeof UsersAdduserRoute
  UsersUsersRoute: typeof UsersUsersRoute
  ProductEditIdRoute: typeof ProductEditIdRoute
  RoleEditIdRoute: typeof RoleEditIdRoute
  StoreEditIdRoute: typeof StoreEditIdRoute
  UsersEditIdRoute: typeof UsersEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/users': {
      id: '/users/users'
      path: '/users/users'
      fullPath: '/users/users'
      preLoaderRoute: typeof UsersUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/adduser': {
      id: '/users/adduser'
      path: '/users/adduser'
      fullPath: '/users/adduser'
      preLoaderRoute: typeof UsersAdduserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/stores': {
      id: '/store/stores'
      path: '/store/stores'
      fullPath: '/store/stores'
      preLoaderRoute: typeof StoreStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/addstore': {
      id: '/store/addstore'
      path: '/store/addstore'
      fullPath: '/store/addstore'
      preLoaderRoute: typeof StoreAddstoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role/role': {
      id: '/role/role'
      path: '/role/role'
      fullPath: '/role/role'
      preLoaderRoute: typeof RoleRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role/addrole': {
      id: '/role/addrole'
      path: '/role/addrole'
      fullPath: '/role/addrole'
      preLoaderRoute: typeof RoleAddroleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/products': {
      id: '/product/products'
      path: '/product/products'
      fullPath: '/product/products'
      preLoaderRoute: typeof ProductProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/add': {
      id: '/product/add'
      path: '/product/add'
      fullPath: '/product/add'
      preLoaderRoute: typeof ProductAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/edit/$id': {
      id: '/users/edit/$id'
      path: '/users/edit/$id'
      fullPath: '/users/edit/$id'
      preLoaderRoute: typeof UsersEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/edit/$id': {
      id: '/store/edit/$id'
      path: '/store/edit/$id'
      fullPath: '/store/edit/$id'
      preLoaderRoute: typeof StoreEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role/edit/$id': {
      id: '/role/edit/$id'
      path: '/role/edit/$id'
      fullPath: '/role/edit/$id'
      preLoaderRoute: typeof RoleEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/edit/$id': {
      id: '/product/edit/$id'
      path: '/product/edit/$id'
      fullPath: '/product/edit/$id'
      preLoaderRoute: typeof ProductEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ProductAddRoute: ProductAddRoute,
  ProductProductsRoute: ProductProductsRoute,
  RoleAddroleRoute: RoleAddroleRoute,
  RoleRoleRoute: RoleRoleRoute,
  StoreAddstoreRoute: StoreAddstoreRoute,
  StoreStoresRoute: StoreStoresRoute,
  UsersAdduserRoute: UsersAdduserRoute,
  UsersUsersRoute: UsersUsersRoute,
  ProductEditIdRoute: ProductEditIdRoute,
  RoleEditIdRoute: RoleEditIdRoute,
  StoreEditIdRoute: StoreEditIdRoute,
  UsersEditIdRoute: UsersEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
